---
- name: Configure ceilometer compute agent
  hosts: nova-compute
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure ceilometer-agent-compute packages are installed
      apt: 
        pkg: "{{ item }}"
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - ceilometer-agent-compute

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items:
        - ceilometer-agent-compute

    - name: ensure ceilometer sqlite is deleted
      file: 
        dest: /var/lib/ceilometer/ceilometer.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/ceilometer/{{ item }}
        dest: /etc/ceilometer/{{ item }}
        owner: ceilometer 
        group: ceilometer 
        mode: 0600
      with_items:
        - ceilometer.conf

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items:
        - ceilometer-agent-compute
