---
- name: Configure neutron-api server
  hosts: neutron-api
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure neutron-api packages are installed
      apt: 
        pkg: neutron-server 
        state: latest 
        update_cache: yes 
        cache_valid_time: 600

    - name: ensure services are stopped
      service: 
        name: neutron-server 
        state: stopped

    - name: ensure neutron sqlite is deleted
      file: 
        dest: /var/lib/neutron/neutron.sqlite 
        state: absent

    - name: update neutron.conf from template
      template: 
        src: templates/etc/neutron/neutron.conf 
        dest: /etc/neutron/neutron.conf 
        owner: neutron 
        group: neutron 
        mode: 0600

    - name: update api-paste.ini from template
      template: 
        src: templates/etc/neutron/api-paste.ini 
        dest: /etc/neutron/api-paste.ini 
        owner: neutron 
        group: neutron 
        mode: 0600

    - name: update ovs_neutron_plugin.ini from template
      template: 
        src: templates/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini 
        dest: /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini 
        owner: neutron 
        group: neutron 
        mode: 0600

    - name: make sure symlink to ovs_neutron_plugin.ini exists
      file: 
        src: /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini 
        dest: /etc/neutron/plugin.ini 
        state: link

    - name: ensure neutron-api services are started and enabled
      service: 
        name: neutron-server 
        state: started 
        enabled: yes

    - name: wait for neutron to come back up
      wait_for:
        host: "{{ neutron_endpoint_host }}"
        port: 9696

    - name: ensure external network is registered
      neutron_network:
        auth_url: "{{ keystone_internal_url }}"
        login_tenant_name: admin
        login_username: admin
        login_password: "{{ admin_password }}"
        name: "{{ external_network_name }}"
        router_external: True
        provider_network_type: gre
        provider_segmentation_id: 6
        state: present

    - name: ensure subnet for external network is registered
      neutron_subnet:
        auth_url: "{{ keystone_internal_url }}"
        login_tenant_name: admin
        login_username: admin
        login_password: "{{ admin_password }}"
        name: "{{ external_network_name }}-subnet"
        network_name: "{{ external_network_name }}"
        cidr: "{{ external_network }}"
        enable_dhcp: False
        gateway_ip: "{{ external_network_gateway_ip }}"
        dns_nameservers: "{{ external_network_dns_nameservers }}"
        allocation_pool_start: "{{ external_network_allocation_pool_start }}"
        allocation_pool_end: "{{ external_network_allocation_pool_end }}"
        state: present
