---
- name: Configure quantum-api server
  hosts: quantum-api
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure quantum-api packages are installed
      apt: 
        pkg: quantum-server 
        state: latest 
        update_cache: yes 
        cache_valid_time: 600

    - name: ensure services are stopped
      service: 
        name: quantum-server 
        state: stopped

    - name: ensure quantum sqlite is deleted
      file: 
        dest: /var/lib/quantum/quantum.sqlite 
        state: absent

    - name: update quantum.conf from template
      template: 
        src: templates/etc/quantum/quantum.conf 
        dest: /etc/quantum/quantum.conf 
        owner: quantum 
        group: quantum 
        mode: 0600

    - name: update ovs_quantum_plugin.ini from template
      template: 
        src: templates/etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini 
        dest: /etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini 
        owner: quantum 
        group: quantum 
        mode: 0600

    - name: make sure symlink to ovs_quantum_plugin.ini exists
      file: 
        src: /etc/quantum/plugins/openvswitch/ovs_quantum_plugin.ini 
        dest: /etc/quantum/plugin.ini 
        state: link

    - name: ensure quantum-api services are started and enabled
      service: 
        name: quantum-server 
        state: started 
        enabled: yes

    - name: wait for quantum to come back up
      wait_for:
        host: "{{ quantum_endpoint_host }}"
        port: 9696

    - name: ensure external network is registered
      quantum_network:
        auth_url: "{{ keystone_internal_url }}"
        login_tenant_name: admin
        login_username: admin
        login_password: "{{ admin_password }}"
        name: "{{ external_network_name }}"
        router_external: True
        provider_network_type: gre
        provider_segmentation_id: 6
        state: present

    - name: ensure subnet for external network is registered
      quantum_subnet:
        auth_url: "{{ keystone_internal_url }}"
        login_tenant_name: admin
        login_username: admin
        login_password: "{{ admin_password }}"
        name: "{{ external_network_subnet_name }}"
        network_name: "{{ external_network_name }}"
        cidr: "{{ external_network_subnet_cidr }}"
        enable_dhcp: False
        gateway_ip: "{{ external_network_subnet_gateway_ip }}"
        allocation_pool_start: "{{ external_network_subnet_allocation_pool_start }}"
        allocation_pool_end: "{{ external_network_subnet_allocation_pool_end }}"
        state: present
