---
- name: Configure heat server
  hosts: heat
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure heat packages are installed
      apt: 
        pkg: "{{ item }}"
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - heat-api
        - heat-api-cfn
        - heat-engine

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items:
        - heat-api
        - heat-api-cfn
        - heat-engine

    - name: ensure heat sqlite is deleted
      file: 
        dest: /var/lib/heat/heat.sqlite 
        state: absent

    - name: update heat.conf from template
      template: 
        src: templates/etc/heat/heat.conf 
        dest: /etc/heat/heat.conf 
        owner: heat 
        group: heat 
        mode: 0600

    - name: update api-paste.ini from template
      template: 
        src: templates/etc/heat/api-paste.ini 
        dest: /etc/heat/api-paste.ini 
        owner: heat 
        group: heat 
        mode: 0600

    - name: ensure database is synced
      command: /usr/bin/heat-manage db_sync

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items:
        - heat-api
        - heat-api-cfn
        - heat-engine
