---
- name: Configure Swift Storage Node
  hosts: swift-storage
  sudo: True
  gather_facts: True
  vars: 
    storage_ip: "{{ hostvars[ansible_hostname]|find_ip(storage_network) }}"
    replication_ip: "{{ hostvars[ansible_hostname]|find_ip(replication_network) }}"
  tasks:

    - name: ensure required base packages are present
      apt: 
        pkg: "{{ item }}" 
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - python-xattr
        - rsync
        - swift
        - swift-account
        - swift-container
        - swift-object
        - xfsprogs

    - name: ensure services are stopped
      service: 
        name: "{{ item }}" 
        state: stopped
      with_items:
        - rsync
        - swift-account
        - swift-account-auditor
        - swift-account-reaper
        - swift-account-replicator
        - swift-container
        - swift-container-auditor
        - swift-container-replicator
        - swift-container-updater
        - swift-object
        - swift-object-auditor
        - swift-object-replicator
        - swift-object-updater

    - name: update rsyncd.conf from template
      template: 
        src: templates/etc/rsyncd.conf 
        dest: /etc/rsyncd.conf 
        owner: root 
        group: root 
        mode: 0644

    - name: enable rsync in /etc/default
      command: sed -i '/^RSYNC_ENABLE=/s/false/true/' /etc/default/rsync

    - name: create /etc/swift directory if not already there
      file:
        path: /etc/swift
        owner: swift
        group: swift
        mode: 0750
        state: directory

    - name: update swift.conf from template
      template: 
        src: templates/etc/swift/swift.conf 
        dest: /etc/swift/swift.conf 
        owner: swift 
        group: swift 
        mode: 0660

    - name: update account-server.conf from template
      template: 
        src: templates/etc/swift/account-server.conf 
        dest: /etc/swift/account-server.conf 
        owner: swift 
        group: swift 
        mode: 0660

    - name: update container-server.conf from template
      template: 
        src: templates/etc/swift/container-server.conf 
        dest: /etc/swift/container-server.conf 
        owner: swift 
        group: swift 
        mode: 0660

    - name: update object-server.conf from template
      template: 
        src: templates/etc/swift/object-server.conf 
        dest: /etc/swift/object-server.conf 
        owner: swift 
        group: swift 
        mode: 0660

    - name: create filesystems on devices
      filesystem:
        dev: /dev/{{ item }}
        fstype: xfs
        opts: -i size=1024
      with_items: storage_devices

    - name: create node directory
      file:
        path: /srv/node
        owner: swift
        group: swift
        mode: 0750
        state: directory

    - name: create device directories
      file:
        path: /srv/node/{{ item }}
        owner: swift
        group: swift
        mode: 0750
        state: directory
      with_items: storage_devices

    - name: mount device directories
      mount: 
        name: /srv/node/{{ item }} 
        src: /dev/{{ item }} 
        fstype: xfs 
        opts: noatime,nodiratime,nobarrier,logbufs=8
        state: mounted
      with_items: storage_devices

    - name: ensure /srv/node is owned by swift
      file:
        path: /srv/node
        owner: swift
        group: swift
        recurse: yes
        state: directory

    - name: create /var/lib/swift directory if not already there
      file:
        path: /var/lib/swift
        owner: swift
        group: swift
        mode: 0750
        state: directory

    - name: create /var/cache/swift directory if not already there
      file:
        path: /var/cache/swift
        owner: swift
        group: swift
        mode: 0750
        state: directory

    - name: ensure rsync service is started
      service: 
        name: rsync
        state: restarted 
        enabled: yes

    - name: create account ring
      delegate_to: "{{ groups['swift-proxy'][0] }}"
      command: sudo -u swift swift-ring-builder account.builder add r1z1-{{ storage_ip }}:6002R{{ replication_ip }}:6005/{{ item }} 100
               chdir=/etc/swift
      with_items: storage_devices
      ignore_errors: yes

    - name: create container ring
      delegate_to: "{{ groups['swift-proxy'][0] }}"
      command: sudo -u swift swift-ring-builder container.builder add r1z1-{{ storage_ip }}:6001R{{ replication_ip }}:6004/{{ item }} 100
               chdir=/etc/swift
      with_items: storage_devices
      ignore_errors: yes

    - name: create object ring
      delegate_to: "{{ groups['swift-proxy'][0] }}"
      command: sudo -u swift swift-ring-builder object.builder add r1z1-{{ storage_ip }}:6000R{{ replication_ip }}:6003/{{ item }} 100
               chdir=/etc/swift
      with_items: storage_devices
      ignore_errors: yes

