---
- name: Install cinder server agents
  hosts: cinder-volume
  sudo: True
  gather_facts: True
  tasks:

    - name: create cinder-volumes volume group
      lvg:
        vg: cinder-volumes
        pvs: "/dev/{{ volume_devices|join(',/dev/') }}"
        state: present

    - name: ensure cinder packages are installed
      apt: 
        pkg: "{{ item }}" 
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - cinder-volume
        - lvm2
        - qemu-utils
        - tgt

    - name: ensure services are stopped
      service: 
        name: "{{ item }}" 
        state: stopped
      with_items: 
        - cinder-volume
        - tgt

    - name: ensure cinder sqlite is deleted
      file: 
        dest: /var/lib/cinder/cinder.sqlite 
        state: absent

    - name: update configuration files from templates
      template: 
        src: templates/etc/cinder/{{ item }}
        dest: /etc/cinder/{{ item }}
        owner: cinder 
        group: cinder 
        mode: 0600
      with_items:
        - cinder.conf
        - api-paste.ini

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items:
        - cinder-volume
        - tgt
