---
- name: Configure cinder-api server
  hosts: cinder-api
  sudo: True
  gather_facts: True
  tasks:

    - name: ensure cinder-api packages are installed
      apt: 
        pkg: "{{ item }}"
        state: latest 
        update_cache: yes 
        cache_valid_time: 600
      with_items:
        - cinder-api
        - cinder-scheduler

    - name: ensure services are stopped
      service: 
        name: "{{ item }}"
        state: stopped
      with_items:
        - cinder-api
        - cinder-scheduler

    - name: ensure cinder sqlite is deleted
      file: 
        dest: /var/lib/cinder/cinder.sqlite 
        state: absent

    - name: update cinder.conf from template
      template: 
        src: templates/etc/cinder/cinder.conf 
        dest: /etc/cinder/cinder.conf 
        owner: cinder 
        group: cinder 
        mode: 0600

    - name: update api-paste.ini from template
      template: 
        src: templates/etc/cinder/api-paste.ini 
        dest: /etc/cinder/api-paste.ini 
        owner: cinder 
        group: cinder 
        mode: 0600

    - name: ensure database is synced
      command: /usr/bin/cinder-manage db sync

    - name: ensure services are started and enabled
      service: 
        name: "{{ item }}"
        state: restarted 
        enabled: yes
      with_items:
        - cinder-api
        - cinder-scheduler
